###
GET http://localhost:8080/package
Content-Type: application/json

###
POST http://localhost:8080/package
Content-Type: application/json

{
    "name": "New Packages"
}

###
GET http://localhost:8080/package/100


###
PATCH http://localhost:8080/package/100
Content-Type: application/json

{
    "name": "New Package Update"
}


###
DELETE http://localhost:8080/package/888888
Content-Type: application/json
