###
GET http://localhost:8080/package
Content-Type: application/json

###
POST http://localhost:8080/package
Content-Type: application/json

{
    "name": "New Packages"
}

###
GET http://localhost:8080/package/1111


###
PATCH http://localhost:8080/package/11111
Content-Type: application/json

{
    "name": "AAA"
}


###
DELETE http://localhost:8080/package/3
Content-Type: application/json
